version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "7070:80"
        volumes:
            - ./:/code
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    redis:
        image: redis:latest
        ports:
            - "6060:6379"
        networks:
            - code-network
    php:
        build: .
        volumes:
            - ./:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge